// <ArrowButton 
// scrollFunction={scrollToEnd} 
// showBtn={!showRightBtn} 
// rightParentVisible={!rightParentVisible} 
// hoverBtnTiming={!hoverBtnTiming} 
// arrowImg={rightScrollBtn} 
// hoverBtnImg={plus} 
// bounceAnimationX={['0%','5%','0%','-5%']} 
// exitScaleX={-.8} 
// squishScaleX={[1,-.87,1,-.95,1]} 
// hoverLeaveStartX={-.8} 
// exitInitialX={"-50%"} 
// arrowDirection={"right-scroll"}>
// </ArrowButton>

// <ArrowButton
// scrollFunction={scrollToEnd} 
// showBtn={showRightBtn} 
// rightParentVisible={rightParentVisible} 
// hoverBtnTiming={hoverBtnTiming} 
// arrowImg={leftScrollBtn} 
// hoverBtnImg={minus} 
// bounceAnimationX={['0%','-5%','0%','5%']} 
// exitScaleX={.8} 
// squishScaleX={[1,.87,1,.95,1]} 
// hoverLeaveStartX={10} 
// exitInitialX={"50%"} 
// arrowDirection={"left-scroll"}>
// </ArrowButton>